---
- name: ansible script to take backups
  hosts: all
  gather_facts: false
  vars:
    base_path: "E:\\deploy"
  tasks:
    - name: get the directory in the deploy path
      win_find:
        paths: "{{base_path}}"  
        #patterns: "*.out"
        recurse: yes
        file_type: directory  
      register: deploypath

    - name: get the deployment path
      debug:
        msg: "{{ deploypath.files | map(attribute='filename') | list  }}" 