---
- name: Get yesterday's date with underscores
  hosts: all
  gather_facts: true
  tasks:
    - name: Get current hour
      set_fact:
        current_hour: "{{ ansible_date_time.hour | int }}"

    - name: Format the date
      set_fact:
        currentdate_: "{{ '%d-%m-%Y' | strftime(ansible_date_time.epoch) }}"
        currentdate_hypen: "{{ '%d-%m-%Y' | strftime(ansible_date_time.epoch) }}"
        currentdate_fullmonth: "{{ '%d-%B-%Y' | strftime(ansible_date_time.epoch) }}"
        currentdate_shortmonth: "{{ '%d-%B-%Y' | strftime(ansible_date_time.epoch) }}"

#    - name: Display the formatted date
#      debug:
#        msg: "Formatted date is {{ currentdate_ }}"
 
    - name: get yesterdays date
      ansible.builtin.shell: "date -d 'yesterday 13:00' '+%d_%m_%Y'"
      register: yesterday_

    - name: get yesterdays date hypen
      ansible.builtin.shell: "date -d 'yesterday 13:00' '+%d-%m-%Y'"
      register: yesterday_hypen

    - name: get yesterdays date fullmonth
      ansible.builtin.shell: "date -d 'yesterday 13:00' '+%d-%B-%Y'"
      register: yesterday_fullm

    - name: get yesterdays date shortmonth
      ansible.builtin.shell: "date -d 'yesterday 13:00' '+%d-%b-%Y'"
      register: yesterday_shortm    

    - name: Get yesterday's date using timestamp subtraction
      set_fact:
 #       yesterday_date: "{{ '%Y-%m-%d'|strftime(ansible_date_time.epoch|int - 86400) }}"
         yesterday_date_: "{{ yesterday_.stdout }}"
         yesterday_date_hypen: "{{ yesterday_hypen.stdout }}"
         yesterday_date_fullm: "{{ yesterday_fullm.stdout }}"
         yesterday_date_shortm: "{{ yesterday_shortm .stdout }}"

    - name: Determine the correct date
      set_fact:
        selected_date: "{{ currentdate_ if current_hour|int >= 20 else yesterday_date_ }}"
        selectdate_date_hypen:  "{{ currentdate_hypen if current_hour|int >= 20 else yesterday_date_hypen }}"
        selected_date_fullm: "{{ currentdate_fullmonth if current_hour|int >= 20 else yesterday_date_fullm }}"
        selected_date_shortm: "{{ currentdate_shortmonth if current_hour|int >= 20 else yesterday_date_shortm }}"
    - name: Display the selected date
      debug:
        msg: 
          - "Selected Date in _: {{ selected_date }}."
          - " Selected date in hypen : {{ selectdate_date_hypen }}." 
          - "Selected Date in fullmonth : {{ selected_date_fullm }}."
          - " Selected date in shortmonth : {{ selected_date_shortm }}." 