---
- name: Get yesterday's date with underscores
  hosts: all
  gather_facts: true
  tasks:
    - debug: 
        msg: "{{ ansible_date_time }}"

    - debug: 
        msg: "the current date is {{ ansible_date_time.date }}"

    - name: Get current hour
      set_fact:
        current_hour: "{{ now().strftime('%H') | int }}"

    - name: Get today's date
      set_fact:
        today_date: "{{ now().strftime('%Y-%m-%d') }}"

    - name: Get yesterday's date using timestamp subtraction
      set_fact:
        yesterday_date: "{{ (now().timestamp() - 86400) | to_datetime('%Y-%m-%d') }}"

    - name: Determine the correct date
      set_fact:
        selected_date: "{{ today_date if current_hour >= 20 else yesterday_date }}"

    - name: Display the selected date
      debug:
        msg: "Selected Date: {{ selected_date }}"  
   # - name: Determine date based on time
  #    set_fact:
  #      selected_date: >-
   #       {% if current_hour >= 20 %}
  #        {{ now().strftime('%Y-%m-%d') }}
  #        {% else %}
  #        {{ (now() - timedelta(days=1)).strftime('%Y-%m-%d') }}
  #        {% endif %}

 #   - name: Display the selected date
  #    debug:
   #     msg: "Selected Date: {{ selected_date }}"