---
- name: Get yesterday's date with underscores
  hosts: all
  tasks:
    - debug:
        msg: "{{ '%Y-%m-%d'|strftime(ansible_date_time.epoch|int - 86400) }}"

    - name: Format yesterday's date with _
      debug:
        msg: "{{ (now() - timedelta(days=1)).strftime('%Y_%m_%d') }}"

    - name: Format yesterday's date with -
      debug:
        msg: "{{ (now() - timedelta(days=1)).strftime('%Y_%m_%d') }}"

    - name: Show today's date with full month name
      debug:
        msg: "{{ (now()- timedelta(days=1)).strftime('%d_%B_%Y') }}"

    - name: Show yesterday's date with abbreviated month
      debug:
        msg: "{{ (now() - timedelta(days=1)).strftime('%d_%b_%Y') }}"        

    - name: Show today's date with full month name
      debug:
        msg: "{{ (now()- timedelta(days=1)).strftime('%d-%B-%Y') }}"

    - name: Show yesterday's date with abbreviated month
      debug:
        msg: "{{ (now() - timedelta(days=1)).strftime('%d-%b-%Y') }}"

    - name: Show today's date with full month name
      debug:
        msg: "{{ (now()- timedelta(days=1)).strftime('%d %B %Y') }}"

    - name: Show yesterday's date with abbreviated month
      debug:
        msg: "{{ (now() - timedelta(days=1)).strftime('%d %b %Y') }}" 

    - name: Get current hour
      set_fact:
        current_hour: "{{ now().strftime('%H') | int }}"

    - name: Determine date based on time
      set_fact:
        selected_date: >-
          {% if current_hour >= 20 %}
          {{ now().strftime('%Y-%m-%d') }}
          {% else %}
          {{ (now() - timedelta(days=1)).strftime('%Y-%m-%d') }}
          {% endif %}

    - name: Display the selected date
      debug:
        msg: "Selected Date: {{ selected_date }}"