---
- name: Get yesterday's date with underscores
  hosts: all
  gather_facts: true
  tasks:
    - name: Get today's date
      set_fact:
        today_date: "{{ lookup('ansible.builtin.date', 'now', '%Y-%m-%d') }}"

    - name: Get yesterday's date
      set_fact:
        yesterday_date: "{{ lookup('ansible.builtin.date', 'now -1d', '%Y-%m-%d') }}"

    - name: Get tomorrow's date
      set_fact:
        tomorrow_date: "{{ lookup('ansible.builtin.date', 'now +1d', '%Y-%m-%d') }}"

    - name: Display the results
      debug:
        msg:
          - "Today's Date: {{ today_date }}"
          - "Yesterday's Date: {{ yesterday_date }}"
          - "Tomorrow's Date: {{ tomorrow_date }}"
