---
- name: Get yesterday's date with underscores
  hosts: all
  gather_facts: true
  tasks:
    - name: Get current hour
      set_fact:
        current_hour: "{{ now().strftime('%H') | int }}"

    - name: Format the date
      set_fact:
        currentdate: "{{ '%Y-%m-%d' | strftime(ansible_date_time.epoch) }}"
        #formatted_date: "{{ current_date | strftime('%Y-%m-%d') }}"

    - name: Display the formatted date
      debug:
        msg: "Formatted date is {{ currentdate }}"

    - name: Get yesterday's date using timestamp subtraction
      set_fact:
        yesterday_date: "{{ '%Y-%m-%d'|strftime(ansible_date_time.epoch|int - 86400) }}"

    - name: Determine the correct date
      set_fact:
        selected_date: "{{ currentdate if current_hour >= 20 else yesterday_date }}"

    - name: Display the selected date
      debug:
        msg: "Selected Date: {{ selected_date }}"