---
- name: Find JSON, XML, and CSV files in a directory
  hosts: all
  gather_facts: no
  tasks:
    - name: Find files with specific extensions
      find:
        paths: "/home/navneet/"  # Change this to your target directory
        patterns: 
          #- "^.*?\\.(xml|json|csv)$"
          - "^.*?\\.({{ item }})$"
        recurse: yes
        use_regex: yes
        read_whole_file: false
        depth: 2
      register: found_files
      with_items:
        - csv
        - json
        - xml
        
    - name: Display found files - csv
      debug:
        msg: "{{ found_files.results[0].files | map(attribute='path') | list }}" 
          # | map(attribute='path') | list |length }}"

    - name: Display found files - json
      debug:
        msg: "{{ found_files.results[1].files | map(attribute='path') | list }}"
          # | map(attribute='path') | list |length }}"

    - name: Display found files - xml
      debug:
        msg: "{{ found_files.results[2].files | map(attribute='path') | list }}"
          # | map(attribute='path') | list |length }}"