---
- name: Find JSON, XML, and CSV files in a directory
  hosts: all
  gather_facts: no
  tasks:
    - name: Find files with specific extensions
      find:
        paths: "/home/navneet/"  # Change this to your target directory
        patterns: 
          #- "^.*?\\.(xml|json|csv)$"
          - "^.*?\\.({{ item }})$"
        recurse: yes
        use_regex: yes
        read_whole_file: false
        depth: 2
        get_checksum: false
      register: found_files
      with_items:
        - csv
        - json
        - xml

    - name: Display found files - csv
      debug:
        msg: "the Totle count is {{ found_files.results[0].files | map(attribute='path') | list | length}}"
        # and path are {{ found_files.results[0].files | map(attribute='path') | list }}" 
          # | map(attribute='path') | list |length }}"

    - name: Display found files - json
      debug:
        msg: "the Totle count is {{ found_files.results[1].files | map(attribute='path') | list | length}}"
        # and path are {{ found_files.results[1].files | map(attribute='path') | list }}"
          # | map(attribute='path') | list |length }}"

    - name: Display found files - xml
      debug:
        msg: "the Totle count is {{ found_files.results[2].files | map(attribute='path') | list | length}}"
        # and path are {{ found_files.results[2].files | map(attribute='path') | list }}"
          # | map(attribute='path') | list |length }}"
          
#- name: Add several users
#  ansible.builtin.user:
#    name: "{{ item.name }}"
#    state: present
#    groups: "{{ item.groups }}"
#  loop:
#    - { name: 'testuser1', groups: 'wheel' }
#    - { name: 'testuser2', groups: 'root' }
          
