---
- name: Trigger a Jenkins Job from Ansible
  hosts: localhost
  tasks:
    - name: Trigger Jenkins job
      community.general.jenkins_job:
        url: "http://192.168.1.7:8080"
        user: "admin"
        token: "11977f02c5c2c6b52a795c03d365fc485c"
        name: "Sample"
        state: "build"
      register: result  

    - name: Show Jenkins response
      debug:
        var: result.json
