---
- name: Trigger a Jenkins Job from Ansible
  hosts: localhost
  tasks:
    - name: Create a jenkins build using basic authentication
      community.general.jenkins_build:
        name: "Sample"
        state: present
        user: admin
        password: primod123
        url: http://192.168.1.7:8080
      register: result  

    - name: Show Jenkins response
      debug:
        var: result.json
