---
- name: Copy and execute a shell script on remote host
  hosts: all
  become: yes
  tasks:
    - name: Copy script to remote host
      copy:
        src: script.sh
        dest: /tmp/myscript.sh
        mode: '0755'

    - name: Execute and check internet connection
      shell: /tmp/myscript.sh
      args:
        stdin: |
          3
          2
          4
          4