---
- name: Copy and execute a shell script on remote host
  hosts: all
  become: yes
  tasks:
    - name: Copy script to remote host
      ansible.builtin.copy:
        src: script.sh
        dest: /tmp/myscript.sh
        mode: '0755'

    - name: Execute and check internet connection
      ansible.builtin.shell: /tmp/myscript.sh
      args:
        stdin_add_newline: false
        stdin: |
          3