---
- name: Copy and execute a shell script on remote host
  hosts: all
  become: yes
  tasks:
    - name: Copy script to remote host
      ansible.builtin.copy:
        src: script.sh
        dest: /tmp/myscript.sh
        mode: '0755'

    - name: check IP addrss
      ansible.builtin.shell: /tmp/myscript.sh
      args:
        stdin_add_newline: false
        stdin: |
          3
          1
          4
      register: output

    - name: display the debug output
      ansible.builtin.debug:
        msg: "{{ output.stdout_lines }}"

    - name: check internet connection
      ansible.builtin.shell: /tmp/myscript.sh
      args:
        stdin_add_newline: false
        stdin: |
          3
          2
          4
      register: output

    - name: display the debug output
      ansible.builtin.debug:
        msg: "{{ output.stdout_lines }}"        

    - name: check uptime
      ansible.builtin.shell: /tmp/myscript.sh
      args:
        stdin_add_newline: false
        stdin: |
          1
          1
          4
      register: output

    - name: display the debug output
      ansible.builtin.debug:
        msg: "{{ output.stdout_lines }}" 

    - name: check the file listing from current directory
      ansible.builtin.shell: /tmp/myscript.sh
      args:
        stdin_add_newline: false
        stdin: |
          2
          1
          4
      register: output

    - name: display the debug output
      ansible.builtin.debug:
        msg: "{{ output.stdout_lines }}"                             