---
- name: Find and display contents of .sql files on Windows
  hosts: windows
  gather_facts: yes
  tasks:

    - name: Search for .sql files in a given path
      win_find:
        paths: "C:\\Users\\nrathi\\Desktop\\nrathi"  
        patterns: "*.sql"
        recurse: yes  
      register: sql_files

    - name: Read and display SQL file contents
      win_shell: "Get-Content -Path '{{ item.path }}' -Raw"
      loop: "{{ sql_files.files }}"
      register: sql_contents
      loop_control:
        label: "{{ item.path }}"
      when: sql_files.files | length > 0

    - name: Show contents of found .sql files
      debug:
        msg: 
          - "File: {{ item.path }}"
          - "Contents: {{ item.stdout }}"
      loop: "{{ sql_contents.results }}"
      loop_control:
        label: "{{ item.path }}"
      when: sql_contents.results is defined
