---
- name: Checkout and Build Code
  hosts: all
  become: yes
  vars:
    git_repo_url: "https://github.com/ravikumarekula/maven-web-project.git"
    git_branch: "main"
    code_checkout_path: "/opt/app"
    build_command: "mvn clean package"   # Replace with mvn clean install, npm install, etc.

  tasks:
  ## added patch to fix the dns
    - name: Clear existing content in /etc/resolv.conf
      copy:
        content: ""
        dest: /etc/resolv.conf
        force: yes

    - name: Add DNS nameservers to /etc/resolv.conf
      lineinfile:
        path: /etc/resolv.conf
        line: "{{ item }}"
        insertafter: EOF
        state: present
      loop:
        - "nameserver 192.168.1.1"
        - "nameserver 8.8.8.8"

    - name: Ensure required packages are installed
      package:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - maven  # Add maven, nodejs, etc., depending on your stack

    - name: Clone repository
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ code_checkout_path }}"
        version: "{{ git_branch }}"
        force: yes

    - name: Build the code
      command: "{{ build_command }}"
      args:
        chdir: "{{ code_checkout_path }}"